name: CI/CD Pipeline

on:
    push:
        branches: [main]
        tags:
            - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
    contents: write
    packages: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: 8.0.x

            - name: Restore
              run: dotnet restore

            - name: Build
              run: dotnet build --configuration Release --no-restore

    package:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - uses: actions/checkout@v4

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: e1enam/usermanager:v1.0.2

    release:
        runs-on: ubuntu-latest
        needs: package
        if: startsWith(github.ref, 'refs/tags/v')
        steps:
            - name: Create GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: ${{ github.ref_name }}
